import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[font]
size = 12

[font.italic]
family = "MonaspiceRn Nerd Font"
style = "Light Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[selection]
save_to_clipboard = false

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"
dynamic_padding = false
dynamic_title = true
opacity = 0.95
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

